name: Build and Release aria2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        run: |
          brew install autoconf automake libtool gettext \
            openssl cppunit libxml2 zlib sqlite3
          brew link --force --overwrite libtool
          brew link --force --overwrite gettext
          echo 'export PATH="/usr/local/opt/libtool/libexec/gnubin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/usr/local/opt/libtool/libexec/gnubin:$PATH"' >> ~/.zshrc
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.zshrc
          source ~/.bash_profile || true
          source ~/.zshrc || true

      - name: Clone aria2
        run: git clone https://github.com/aria2/aria2.git --depth=1

      - name: Build aria2 (macOS)
        run: |
          cd aria2
          glibtoolize --force
          autoreconf -fiv
          ./configure --disable-nls --enable-static --disable-shared
          # حذف پوشه po و ایجاد پوشه po خالی با یک Makefile ساده جهت جلوگیری از خطا
          rm -rf po
          mkdir po
          echo -e 'all:\n\t@echo "Skipping po build."' > po/Makefile
          make -j$(sysctl -n hw.logicalcpu)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-macos
          path: aria2/src/aria2c*
