name: Build and Release aria2

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: runner.os == 'macos-latest'
        run: |
          brew install autoconf automake libtool gettext \
            openssl cppunit libxml2 zlib sqlite3
          brew link --force --overwrite libtool
          brew link --force --overwrite gettext
          echo 'export PATH="/usr/local/opt/libtool/libexec/gnubin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/usr/local/opt/libtool/libexec/gnubin:$PATH"' >> ~/.zshrc
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.zshrc
          source ~/.bash_profile || true
          source ~/.zshrc || true

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: autoconf automake libtool gettext make

      - name: Clone aria2
        run: git clone https://github.com/aria2/aria2.git --depth=1

      - name: Build aria2 (macOS)
        if: runner.os == 'macos-latest'
        run: |
          cd aria2
          glibtoolize --force
          autoreconf -fiv
          ./configure --disable-nls --enable-static --disable-shared
          rm -rf po
          mkdir po
          echo -e 'all:\n\t@echo "Skipping po build."' > po/Makefile
          make -j$(sysctl -n hw.logicalcpu)

      - name: Build aria2 (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd aria2
          # تنظیم متغیر محیطی NLS_DISABLE به‌صورت مستقیم برای جلوگیری از فراخوانی autopoint
          env NLS_DISABLE=1 autoreconf -i
          ./configure --disable-nls --enable-static --disable-shared
          make -j$(echo $NUMBER_OF_PROCESSORS)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-${{ runner.os }}
          path: aria2/src/aria2c*
