name: Build and Release aria2

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y autoconf automake autopoint gettext autotools-dev \
            build-essential pkg-config libtool \
            libssl-dev libcppunit-dev libxml2-dev zlib1g-dev \
            libsqlite3-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install autoconf automake libtool gettext \
            openssl cppunit libxml2 zlib sqlite3
          brew link --force gettext

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y mingw make

      - name: Clone aria2
        run: git clone https://github.com/aria2/aria2.git --depth=1

      - name: Build aria2 (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd aria2
          autoreconf -i
          ./configure --enable-static --disable-shared
          make -j$(nproc)

      - name: Build aria2 (Windows)
        if: runner.os == 'Windows'
        run: |
          cd aria2
          sh ./configure --enable-static --disable-shared
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-${{ runner.os }}
          path: aria2/src/aria2c*
